# Generated by Django 5.1.7 on 2025-05-17 15:07

import django.db.models.deletion
import tracks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
        ('artists', '0001_initial'),
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('file', models.FileField(max_length=500, upload_to='tracks/', validators=[tracks.models.validate_audio_file])),
                ('music_video', models.FileField(blank=True, default='No video available', max_length=500, null=True, upload_to='music_videos/', validators=[tracks.models.validate_audio_file])),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('is_downloadable', models.BooleanField(default=True)),
                ('track_thumbnail', models.ImageField(blank=True, null=True, upload_to='track_thumbnails/')),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumbnails/')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='albums.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='artists.artist')),
                ('genres', models.ManyToManyField(blank=True, related_name='tracks', to='genres.genre')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title'], name='tracks_trac_title_78f644_idx'), models.Index(fields=['artist'], name='tracks_trac_artist__403d03_idx'), models.Index(fields=['album'], name='tracks_trac_album_i_9a7dd3_idx')],
            },
        ),
    ]
