# Generated by Django 5.1.7 on 2025-06-08 11:38

import tracks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_remove_track_music_video_track_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='file',
            field=models.FileField(max_length=500, upload_to=tracks.models.get_audio_upload_path, validators=[tracks.models.validate_audio_file]),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=tracks.models.get_track_image_path),
        ),
        migrations.AlterField(
            model_name='track',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=tracks.models.get_video_upload_path),
        ),
        migrations.AlterField(
            model_name='track',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=tracks.models.get_video_thumbnail_path),
        ),
    ]
