# Generated by Django 5.1.7 on 2025-06-15 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0006_update_audio_paths'),
        ('tracks', 'update_track_paths'),
    ]

    operations = [
    ]
