# Generated by Django 5.1.6 on 2025-03-04 09:11

import music.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_remove_track_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='tracks/', validators=[music.models.validate_audio_file]),
        ),
    ]
