# Generated by Django 5.1.6 on 2025-03-04 09:12

import music.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_track_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='tracks/', validators=[music.models.validate_audio_file]),
        ),
    ]
