# Generated by Django 5.1.6 on 2025-03-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_track_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
    ]
