# Generated by Django 5.1.7 on 2025-03-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_alter_album_options_alter_artist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
