# Generated by Django 5.1.7 on 2025-03-27 08:45

import music.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_alter_artist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='music_video',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='music_videos/', validators=[music.models.validate_audio_file]),
        ),
    ]
