# Generated by Django 5.1.6 on 2025-03-04 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_track_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='file',
        ),
    ]
