# Generated by Django 5.1.7 on 2025-03-23 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_alter_track_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-release_date']},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='playlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-1-1 00:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='music.album'),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('title', 'artist')},
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['title'], name='music_track_title_98819a_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['artist'], name='music_track_artist__0d05f5_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['album'], name='music_track_album_i_dc173d_idx'),
        ),
    ]
