# Generated by Django 5.1.7 on 2025-05-10 08:12

import music.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_genre_track_download_count_track_is_downloadable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='music_video',
            field=models.FileField(blank=True, default='No video available', max_length=500, null=True, upload_to='music_videos/', validators=[music.models.validate_audio_file]),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
