# Generated by Django 5.1.7 on 2025-05-17 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_alter_track_music_video_delete_favorite'),
        ('user', '0004_alter_profile_favorite_albums_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='album',
        ),
        migrations.RemoveField(
            model_name='track',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='track',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='tracks',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='playlist',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='track',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='user',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
