# Generated by Django 5.1.7 on 2025-05-17 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_remove_track_album_remove_track_artist_and_more'),
        ('user', '0005_alter_profile_favorite_albums_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Track',
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
