version: '3.8'

services:
    db:
        image: postgres:14
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_DB=sptf
            - POSTGRES_USER=postgres_sptf
            - POSTGRES_PASSWORD=nam
        ports:
            - '5432:5432'
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres_sptf -d sptf']
            interval: 5s
            timeout: 5s
            retries: 5

    web:
        build: .
        network_mode: 'host'
        environment:
            - DEBUG=True
            - DB_HOST=localhost
            - DB_NAME=sptf
            - DB_USER=postgres_sptf
            - DB_PASSWORD=nam
            - DB_PORT=5432
            - DJANGO_ENV=dev
        ports:
            - '8000:8000'
        volumes:
            - .:/app
        depends_on:
            db:
                condition: service_healthy
        command: './entrypoint.sh'

volumes:
    postgres_data:
