services:
  # Django Web Service
  - type: web
    name: spotify-django-backend
    env: docker
    dockerfilePath: ./Dockerfile.render
    region: oregon
    plan: free
    healthCheckPath: /api/health/
    envVars:
      - key: DEBUG
        value: false
      - key: DJANGO_ENV
        value: production
      - key: DJANGO_SETTINGS_MODULE
        value: spotify.settings_render
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "spotify-django-backend.onrender.com,localhost,127.0.0.1"
      - key: DB_HOST
        value: dpg-d0nhhbemcj7s73e10oo0-a
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: harmonia_n6aa
      - key: DB_USER
        value: harmonia
      - key: DB_PASSWORD
        value: XNQEKZXJqwFoHVuFqQJcX1ndaVAhm8oc
      - key: WAIT_FOR_DB
        value: true

databases:
  - name: harmonia-database
    databaseName: harmonia_n6aa
    user: harmonia
    plan: free 