# Generated by Django 5.1.7 on 2025-05-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='followers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
