# Generated by Django 5.1.7 on 2025-06-15 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_add_description'),
        ('playlists', '0003_playlist_followers'),
    ]

    operations = [
    ]
