# Generated by Django 5.1.7 on 2025-06-15 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_add_image_field'),
        ('playlists', '0004_merge_0003_add_description_0003_playlist_followers'),
    ]

    operations = [
    ]
