# Generated by Django 5.1.7 on 2025-05-17 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('release_date', models.DateField(blank=True, default=None, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='cover_img/album/')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='artists.artist')),
            ],
            options={
                'ordering': ['-release_date'],
                'unique_together': {('title', 'artist')},
            },
        ),
    ]
