# Generated by Django 5.1.7 on 2025-06-15 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_add_image_field'),
        ('albums', '0002_album_description'),
    ]

    operations = [
    ]
