# Generated by Django 5.1.7 on 2025-06-15 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_merge_0002_add_image_field_0002_album_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='cover',
        ),
    ]
