# Generated by Django 5.1.7 on 2025-03-27 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_track_music_video'),
        ('user', '0002_profile_favorite_albums_profile_favorite_artists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='playlists',
            field=models.ManyToManyField(blank=True, related_name='users', to='music.playlist'),
        ),
        migrations.AddField(
            model_name='profile',
            name='recently_played',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_listeners', to='music.track'),
        ),
    ]
