# Generated by Django 5.1.7 on 2025-06-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_queue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuetrack',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queuetrack',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
