version: '3.8'

services:
  web:
    build: .
    environment:
      - DJANGO_ENV=production  # Chỉ định môi trường là production
      - DB_HOST=your-rds-endpoint.amazonaws.com  # Endpoint của RDS
      - DB_NAME=your_rds_db_name
      - DB_USER=your_rds_db_user
      - DB_PASSWORD=your_rds_db_password
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
