version: '3.8'

services:
    web:
        build: .
        entrypoint: ["/app/entrypoint.sh"]
        ports:
            - '8000:8000'
        env_file:
            - .env
        depends_on:
            redis:
                condition: service_healthy
        healthcheck:
            test: ['CMD-SHELL', 'sleep 5 && curl -f http://localhost:8000/health/ || exit 1']
            interval: 30s
            timeout: 10s
            retries: 5

    redis:
        image: redis:7
        restart: always
        ports:
            - '6379:6379'
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            interval: 30s
            timeout: 10s
            retries: 5
