# Generated by Django 5.1.7 on 2025-05-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('bio', models.TextField(blank=True, default='No bio available', null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='artists/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
