# Generated by Django 5.1.7 on 2025-06-15 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_artist_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='avatar',
        ),
    ]
