# Generated by Django 5.1.7 on 2025-03-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('tracks', '0001_initial'),
        ('albums', '0001_initial'),
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_albums',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='albums.album'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_artists',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='artists.artist'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_tracks',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='tracks.track'),
        ),
    ]
