# Generated by Django 5.1.7 on 2025-04-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_genre_track_download_count_track_is_downloadable_and_more'),
        ('user', '0003_profile_playlists_profile_recently_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_albums',
            field=models.ManyToManyField(blank=True, related_name='favorited_by_profiles', to='music.album'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_artists',
            field=models.ManyToManyField(blank=True, related_name='favorited_by_profiles', to='music.artist'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_tracks',
            field=models.ManyToManyField(blank=True, related_name='favorited_by_profiles', to='music.track'),
        ),
    ]
