# Generated by Django 5.1.7 on 2025-05-17 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '__first__'),
        ('artists', '__first__'),
        ('playlists', '__first__'),
        ('tracks', '__first__'),
        ('user', '0004_alter_profile_favorite_albums_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_albums',
            field=models.ManyToManyField(blank=True, related_name='favorited_by_profiles', to='albums.album'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_artists',
            field=models.ManyToManyField(blank=True, related_name='favorited_by_profiles', to='artists.artist'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_tracks',
            field=models.ManyToManyField(blank=True, related_name='favorited_by_profiles', to='tracks.track'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='playlists',
            field=models.ManyToManyField(blank=True, related_name='users', to='playlists.playlist'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='recently_played',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_listeners', to='tracks.track'),
        ),
    ]
